# Generated by Django 3.2.13 on 2022-06-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='author1', max_length=255),
            preserve_default=False,
        ),
    ]
