# Generated by Django 3.2.13 on 2022-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220615_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Good'), (3, 'Fine'), (4, 'Amazing'), (5, 'Awesome')], null=True),
        ),
    ]
